In [1]:
import numpy as np

In [20]:
X=np.array([[3,3],[4,3],[1,1]])
Y=np.array([1,1,-1])

实现求解Gram矩阵函数

In [34]:
def compute_Gram(X):
    N=X.shape[0]
    G=np.zeros((N,N))
    for i in range(N):
        for j in range(N):
            G[i][j]=np.dot(X[i],X[j])
    return G

验证一下Gram矩阵G

In [35]:
G=compute_Gram(X)

In [36]:
G

array([[18., 21.,  6.],
       [21., 25.,  7.],
       [ 6.,  7.,  2.]])

接下来实现感知机对偶形式求解超平面函数

In [123]:
def Train_w_b(X,Y):
    G=compute_Gram(X)
    N=X.shape[0]           #N为样本个数
    a=np.zeros(N)
    b=0
    count=0#记录迭代次数
    i=0
    while i<N:
        count+=1
        for i in range(N):
            if(Y[i]*(np.dot(a*Y,G[i])+b))<=0:
                a[i]+=1
                b+=Y[i]
                break
            else:       #遍历完全部样本而且都正确,这一次迭代不算，因为这一次没有任何修改，所以最后输出的迭代次数要-1
                if i==N-1:
                    return a,b,count-1

In [124]:
a,b,count=Train_w_b(X,Y)

可以看到如下结果与答案一样，总迭代次数为7，求解的超平面参数w=[1,1],b=-3

In [125]:
a

array([2., 0., 5.])

In [126]:
b

-3

In [127]:
count

7

In [128]:
w=np.dot(a*Y,X)

In [129]:
w

array([1., 1.])